# Generated by Django 2.2.7 on 2019-11-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otusblog', '0002_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
