# Generated by Django 2.2.7 on 2019-11-14 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otusblog', '0003_remove_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='otusblog.Publisher'),
            preserve_default=False,
        ),
    ]
