# Generated by Django 2.2.7 on 2019-11-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otusblog', '0004_article_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('f', 'foo'), ('b', 'bar'), ('s', 'spam'), ('e', 'eggs')], default='f', max_length=1),
            preserve_default=False,
        ),
    ]
